<?php
/*
配置文件
*/
	define('DB_NAME','image_lib');
	define('DB_HOST','localhost');
	define('DB_USER','root');
	define('DB_PWD','');
	define('TEMPLATES_PATH','./templates/default/');
	define('SCHOOL_NAME',"新昌县城西小学");
	define('VERSION',"3.0");
	define('ADMIN_USER',"tmnet");
	define('ADMIN_PWD',"12345678");
?>